### PR TITLE
Added stick control

### PR DESCRIPTION
**Pull request by i0x0**
uh just why not

p.s. it **def** lags when u spin the sticks around

### CODE REVIEW

**Comment by TooTallNate** [comment]
Awesome! Very cool. Could I ask you to:
1. Remove the Bun lock file
2. Revert the unrelated formatting changes?

**Comment by TooTallNate** [comment]
Regarding the lagging, I'm sure there's some optimizations to the rendering code that could help (caching of "static" parts for example). Also, I wonder how much [overclocking](https://nxjs.n8.io/clkrst) would help.

**Comment by i0x0** [comment]
> Regarding the lagging, I'm sure there's some optimizations to the rendering code that could help (caching of "static" parts for example). Also, I wonder how much [overclocking](https://nxjs.n8.io/clkrst) would help.

Pertaining the lag, if i just turn up the axis threshold the lag is barely noticable unless you're actually trying to force it to

**Comment by TooTallNate** [comment]
Merged! I ended up reverting the undo and dark mode stuff. I'm not really interested in undo - the risk is part of the game 😄 I would be down for dark mode though, so submit a new PR if you're still interested in adding that.

**Pull request merged**
